version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - redis

  notifications:
    build:
      context: .
      dockerfile: ./notifications/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
networks:
  microservices-network:
    driver: bridge
